### ISSUE TITLE
inconsistent label  subject / subject-name

### ISSUE THREAD

**Issue by fridim** [redhat-cop/anarchy#36]
Depending on the resource you want to filter with label, you need to use either `subject=...` or `subject-name=...`

Example:

```
oc get anarchyevents -l   anarchy.gpte.redhat.com/subject-name=gpte.babylon-ocp4-workshop.dev-vzc5n

oc get anarchyactions  -l anarchy.gpte.redhat.com/subject=gpte.babylon-ocp4-workshop.dev-vzc5n
```

I would expect the label name to be the consistent across Anarchy resources

**Comment by jkupferer** [comment]
Fixed, all labels now use `anarchy.gpte.redhat.com/subject`
